# Generated by Django 4.2.7 on 2024-04-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saveNote', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFile',
            new_name='SaveNote',
        ),
        migrations.RenameField(
            model_name='savenote',
            old_name='upload_file',
            new_name='saveNote',
        ),
    ]
