# Generated by Django 4.2.7 on 2024-04-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deleteFile", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deletefile",
            old_name="delete_file",
            new_name="deleteFile",
        ),
    ]
