version: '3.12'

services:
  django:
    container_name: django
    ports:
      - 8000:8000
    build:
      context: ./djangogirlsVenv
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangogirlsVenv/myproject:/djangogirls/djangogirlsVenv/myproject


    environment:
      - DEBUG=1
    working_dir: /djangogirls/djangogirlsVenv/myproject