# Generated by Django 4.2.7 on 2024-04-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_content', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
