FROM python:3.12.0-alpine

WORKDIR /djangogirls/djangogirls_venv/myproject

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY ./requirements.txt /djangogirls/djangogirls_venv/myproject/requirements.txt
RUN pip install -r requirements.txt

COPY entrypoint.sh /djangogirls/djangogirls_venv/entrypoint.sh

COPY . /djangogirls/djangogirls_venv/myproject

ENTRYPOINT ["/djangogirls/djangogirls_venv/entrypoint.sh"]
