# Generated by Django 4.2.7 on 2024-04-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getinfo',
            old_name='get_info',
            new_name='getInfo',
        ),
    ]
