# Generated by Django 4.2.7 on 2024-04-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newMediaFile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFile',
            new_name='NewMediaFile',
        ),
        migrations.RenameField(
            model_name='newmediafile',
            old_name='upload_file',
            new_name='newMediaFile',
        ),
    ]
