FROM python:3.12.0-alpine

WORKDIR /djangogirls/djangogirlsVenv/myproject

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY ./requirements.txt /djangogirls/djangogirlsVenv/myproject/requirements.txt
RUN pip install -r requirements.txt

# COPY entrypoint.sh /djangogirls/djangogirlsVenv/entrypoint.sh

COPY . /djangogirls/djangogirlsVenv/myproject

# ENTRYPOINT ["/djangogirls/djangogirlsVenv/entrypoint.sh"]
