# Generated by Django 4.2.7 on 2024-04-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updateInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateinfo',
            old_name='update_info',
            new_name='updateInfo',
        ),
    ]
