# Generated by Django 4.2.7 on 2023-12-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
