# Generated by Django 5.0.3 on 2024-03-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_content', '0002_savecontent_delete_react'),
    ]

    operations = [
        migrations.AddField(
            model_name='savecontent',
            name='content',
            field=models.CharField(default='default_value_here', max_length=100),
        ),
    ]
