# Generated by Django 4.2.7 on 2024-04-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updateMediaFile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdateFile',
            new_name='UpdateMediaFile',
        ),
        migrations.RenameField(
            model_name='updatemediafile',
            old_name='update_file',
            new_name='updateMediaFile',
        ),
    ]
