# Generated by Django 4.2.7 on 2024-04-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deleteNote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleteNote', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
