# Generated by Django 4.2.7 on 2024-04-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgetPassword', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forgetPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SigninStatus',
        ),
    ]
